<a href="https://colab.research.google.com/github/pradeep10kumar/Accelerometer-data_analysis/blob/master/LLM_Post_Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Supervised Fine-Tuning (SFT)

In [ ]:
# Remove any remnants of broken packages
!pip uninstall -y torch torchvision torchaudio transformers datasets trl jinja2 markupsafe tabulate pandas numpy huggingface-hub

# Install only the *compatible* versions needed for your workflow
!pip install --upgrade pip
!pip install torch==2.3.0
!pip install "numpy<2"
#!pip install "transformers>=4.52.0,<5.0"
!pip install git+https://github.com/huggingface/transformers.git
!pip install "datasets>=3.6.0,<4.0.0"
!pip install "trl==0.14.0"
!pip install "huggingface-hub>=0.34.0,<1.0"
!pip install "tabulate==0.9.0"
!pip install "jinja2>=3.1.2"
!pip install "markupsafe>=2.1.1"

Found existing installation: torch 2.7.1
Uninstalling torch-2.7.1:
  Successfully uninstalled torch-2.7.1
Found existing installation: torchvision 0.22.1
Uninstalling torchvision-0.22.1:
  Successfully uninstalled torchvision-0.22.1
WARNING: Skipping torchaudio as it is not installed.
Found existing installation: transformers 4.54.1
Uninstalling transformers-4.54.1:
  Successfully uninstalled transformers-4.54.1
Found existing installation: datasets 3.6.0
Uninstalling datasets-3.6.0:
  Successfully uninstalled datasets-3.6.0
Found existing installation: trl 0.14.0
Uninstalling trl-0.14.0:
  Successfully uninstalled trl-0.14.0
Found existing installation: Jinja2 3.1.6
Uninstalling Jinja2-3.1.6:
  Successfully uninstalled Jinja2-3.1.6
Found existing installation: MarkupSafe 3.0.2
Uninstalling MarkupSafe-3.0.2:
  Successfully uninstalled MarkupSafe-3.0.2
Found existing installation: tabulate 0.9.0
Uninstalling tabulate-0.9.0:
  Successfully uninstalled tabulate-0.9.0
Found existing installation: pandas 2.3.1
Uninstalling pandas-2.3.1:
  Successfully uninstalled pandas-2.3.1
Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4
Found existing installation: huggingface-hub 0.34.3
Uninstalling huggingface-hub-0.34.3:
  Successfully uninstalled huggingface-hub-0.34.3
Requirement already satisfied: pip in /usr/local/lib/python3.11/dist-packages (25.2)
Collecting torch==2.3.0
  Using cached torch-2.3.0-cp311-cp311-manylinux1_x86_64.whl.metadata (26 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch==2.3.0) (3.18.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.11/dist-packages (from torch==2.3.0) (4.14.1)
Requirement already satisfied: sympy in /usr/local/lib/python3.11/dist-packages (from torch==2.3.0) (1.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch==2.3.0) (3.5)
Collecting jinja2 (from torch==2.3.0)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch==2.3.0) (2025.3.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch==2.3.0)
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch==2.3.0)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch==2.3.0)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch==2.3.0)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch==2.3.0)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch==2.3.0)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch==2.3.0)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch==2.3.0)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch==2.3.0)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-nccl-cu12==2.20.5 (from torch==2.3.0)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch==2.3.0)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.7 kB)
Collecting triton==2.3.0 (from torch==2.3.0)
  Using cached triton-2.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.11/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch==2.3.0) (12.6.85)
Collecting MarkupSafe>=2.0 (from jinja2->torch==2.3.0)
  Using cached MarkupSafe-3.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy->torch==2.3.0) (1.3.0)
Using cached torch-2.3.0-cp311-cp311-manylinux1_x86_64.whl (779.2 MB)
Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
Using cached triton-2.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (168.1 MB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached MarkupSafe-3.0.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (23 kB)
Installing collected packages: triton, nvidia-nvtx-cu12, nvidia-nccl-cu12, nvidia-cusparse-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, MarkupSafe, nvidia-cusolver-cu12, nvidia-cudnn-cu12, jinja2, torch
  Attempting uninstall: triton
    Found existing installation: triton 3.3.1
    Uninstalling triton-3.3.1:
      Successfully uninstalled triton-3.3.1
  Attempting uninstall: nvidia-nvtx-cu12
    Found existing installation: nvidia-nvtx-cu12 12.6.77
    Uninstalling nvidia-nvtx-cu12-12.6.77:
      Successfully uninstalled nvidia-nvtx-cu12-12.6.77
  Attempting uninstall: nvidia-nccl-cu12
    Found existing installation: nvidia-nccl-cu12 2.26.2
    Uninstalling nvidia-nccl-cu12-2.26.2:
      Successfully uninstalled nvidia-nccl-cu12-2.26.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.4.2
    Uninstalling nvidia-cusparse-cu12-12.5.4.2:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.4.2
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.7.77
    Uninstalling nvidia-curand-cu12-10.3.7.77:
      Successfully uninstalled nvidia-curand-cu12-10.3.7.77
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.3.0.4
    Uninstalling nvidia-cufft-cu12-11.3.0.4:
      Successfully uninstalled nvidia-cufft-cu12-11.3.0.4
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.6.77
    Uninstalling nvidia-cuda-runtime-cu12-12.6.77:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.6.77
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.6.77
    Uninstalling nvidia-cuda-nvrtc-cu12-12.6.77:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.6.77
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.6.80
    Uninstalling nvidia-cuda-cupti-cu12-12.6.80:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.6.80
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.6.4.1
    Uninstalling nvidia-cublas-cu12-12.6.4.1:
      Successfully uninstalled nvidia-cublas-cu12-12.6.4.1
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.7.1.2
    Uninstalling nvidia-cusolver-cu12-11.7.1.2:
      Successfully uninstalled nvidia-cusolver-cu12-11.7.1.2
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.5.1.17
    Uninstalling nvidia-cudnn-cu12-9.5.1.17:
      Successfully uninstalled nvidia-cudnn-cu12-9.5.1.17
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15/15 [torch]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
accelerate 1.9.0 requires huggingface_hub>=0.21.0, which is not installed.
accelerate 1.9.0 requires numpy<3.0.0,>=1.17, which is not installed.
folium 0.20.0 requires numpy, which is not installed.
timm 1.0.19 requires huggingface_hub, which is not installed.
timm 1.0.19 requires torchvision, which is not installed.
bokeh 3.7.3 requires numpy>=1.16, which is not installed.
bokeh 3.7.3 requires pandas>=1.2, which is not installed.
fastai 2.7.19 requires pandas, which is not installed.
fastai 2.7.19 requires torchvision>=0.11, which is not installed.
cudf-cu12 25.6.0 requires numpy<3.0a0,>=1.23, which is not installed.
cudf-cu12 25.6.0 requires pandas<2.2.4dev0,>=2.0, which is not installed.
gradio 5.38.2 requires huggingface-hub>=0.28.1, which is not installed.
gradio 5.38.2 requires numpy<3.0,>=1.0, which is not installed.
gradio 5.38.2 requires pandas<3.0,>=1.0, which is not installed.
pylibraft-cu12 25.6.0 requires numpy<3.0a0,>=1.23, which is not installed.
sentence-transformers 4.1.0 requires huggingface-hub>=0.20.0, which is not installed.
sentence-transformers 4.1.0 requires transformers<5.0.0,>=4.41.0, which is not installed.
peft 0.16.0 requires huggingface_hub>=0.25.0, which is not installed.
peft 0.16.0 requires numpy>=1.17, which is not installed.
peft 0.16.0 requires transformers, which is not installed.
holoviews 1.21.0 requires numpy>=1.21, which is not installed.
holoviews 1.21.0 requires pandas>=1.3, which is not installed.
cuml-cu12 25.6.0 requires numpy<3.0a0,>=1.23, which is not installed.
panel 1.7.5 requires pandas>=1.2, which is not installed.
cuvs-cu12 25.6.1 requires numpy<3.0a0,>=1.23, which is not installed.
osqp 1.0.4 requires numpy>=1.7, which is not installed.
geemap 0.35.3 requires numpy, which is not installed.
geemap 0.35.3 requires pandas, which is not installed.
xgboost 3.0.2 requires numpy, which is not installed.
dask-cudf-cu12 25.6.0 requires numpy<3.0a0,>=1.23, which is not installed.
dask-cudf-cu12 25.6.0 requires pandas<2.2.4dev0,>=2.0, which is not installed.
spacy 3.8.7 requires numpy>=1.19.0; python_version >= "3.9", which is not installed.
Successfully installed MarkupSafe-3.0.2 jinja2-3.1.6 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.20.5 nvidia-nvtx-cu12-12.1.105 torch-2.3.0 triton-2.3.0
Collecting numpy<2
  Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
Installing collected packages: numpy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
accelerate 1.9.0 requires huggingface_hub>=0.21.0, which is not installed.
tsfresh 0.21.0 requires pandas>=0.25.0, which is not installed.
dopamine-rl 4.1.2 requires pandas>=0.24.2, which is not installed.
tensorflow-decision-forests 1.11.0 requires pandas, which is not installed.
bokeh 3.7.3 requires pandas>=1.2, which is not installed.
pymc 5.25.1 requires pandas>=0.24.0, which is not installed.
geopandas 1.1.1 requires pandas>=2.0.0, which is not installed.
cudf-cu12 25.6.0 requires pandas<2.2.4dev0,>=2.0, which is not installed.
plotnine 0.14.5 requires pandas>=2.2.0, which is not installed.
prophet 1.1.7 requires pandas>=1.0.4, which is not installed.
gradio 5.38.2 requires huggingface-hub>=0.28.1, which is not installed.
gradio 5.38.2 requires pandas<3.0,>=1.0, which is not installed.
diffusers 0.34.0 requires huggingface-hub>=0.27.0, which is not installed.
mizani 0.13.5 requires pandas>=2.2.0, which is not installed.
pandas-gbq 0.29.2 requires pandas>=1.1.4, which is not installed.
yfinance 0.2.65 requires pandas>=1.3.0, which is not installed.
arviz 0.22.0 requires pandas>=2.1.0, which is not installed.
statsmodels 0.14.5 requires pandas!=2.1.0,>=1.4, which is not installed.
torchtune 0.6.1 requires datasets, which is not installed.
torchtune 0.6.1 requires huggingface_hub[hf_transfer], which is not installed.
peft 0.16.0 requires huggingface_hub>=0.25.0, which is not installed.
peft 0.16.0 requires transformers, which is not installed.
holoviews 1.21.0 requires pandas>=1.3, which is not installed.
dask-cuda 25.6.0 requires pandas>=1.3, which is not installed.
cufflinks 0.17.3 requires pandas>=0.19.2, which is not installed.
mlxtend 0.23.4 requires pandas>=0.24.2, which is not installed.
panel 1.7.5 requires pandas>=1.2, which is not installed.
bigframes 2.12.0 requires pandas>=1.5.3, which is not installed.
bigframes 2.12.0 requires tabulate>=0.9, which is not installed.
shap 0.48.0 requires pandas, which is not installed.
sklearn-pandas 2.2.0 requires pandas>=1.1.4, which is not installed.
bqplot 0.12.45 requires pandas<3.0.0,>=1.0.0, which is not installed.
cmdstanpy 1.2.5 requires pandas, which is not installed.
geemap 0.35.3 requires pandas, which is not installed.
db-dtypes 1.4.3 requires pandas>=1.5.3, which is not installed.
seaborn 0.13.2 requires pandas>=1.2, which is not installed.
dask-cudf-cu12 25.6.0 requires pandas<2.2.4dev0,>=2.0, which is not installed.
libpysal 4.13.0 requires pandas>=1.4, which is not installed.
xarray 2025.7.1 requires pandas>=2.2, which is not installed.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4

Collecting git+https://github.com/huggingface/transformers.git
  Cloning https://github.com/huggingface/transformers.git to /tmp/pip-req-build-apkm0p4n
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers.git /tmp/pip-req-build-apkm0p4n
  Resolved https://github.com/huggingface/transformers.git to commit 4fcf45551775b05a3a78481ad53552635026c7d2
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers==4.55.0.dev0) (3.18.0)
Collecting huggingface-hub<1.0,>=0.34.0 (from transformers==4.55.0.dev0)
  Using cached huggingface_hub-0.34.3-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers==4.55.0.dev0) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers==4.55.0.dev0) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers==4.55.0.dev0) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers==4.55.0.dev0) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers==4.55.0.dev0) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers==4.55.0.dev0) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers==4.55.0.dev0) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers==4.55.0.dev0) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.55.0.dev0) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.55.0.dev0) (4.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.55.0.dev0) (1.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.55.0.dev0) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.55.0.dev0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.55.0.dev0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.55.0.dev0) (2025.7.14)
Using cached huggingface_hub-0.34.3-py3-none-any.whl (558 kB)
Building wheels for collected packages: transformers
  Building wheel for transformers (pyproject.toml) ... done
  Created wheel for transformers: filename=transformers-4.55.0.dev0-py3-none-any.whl size=12136384 sha256=981da992a999128e11759532d8f6e552e093f24dcb5c6852999e745b6a58a288
  Stored in directory: /tmp/pip-ephem-wheel-cache-02fo48u6/wheels/32/4b/78/f195c684dd3a9ed21f3b39fe8f85b48df7918581b6437be143
Successfully built transformers
Installing collected packages: huggingface-hub, transformers
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [transformers]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
timm 1.0.19 requires torchvision, which is not installed.
gradio 5.38.2 requires pandas<3.0,>=1.0, which is not installed.
torchtune 0.6.1 requires datasets, which is not installed.
Successfully installed huggingface-hub-0.34.3 transformers-4.55.0.dev0
Collecting datasets<4.0.0,>=3.6.0
  Using cached datasets-3.6.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets<4.0.0,>=3.6.0) (3.18.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets<4.0.0,>=3.6.0) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets<4.0.0,>=3.6.0) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets<4.0.0,>=3.6.0) (0.3.8)
Collecting pandas (from datasets<4.0.0,>=3.6.0)
  Using cached pandas-2.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (91 kB)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets<4.0.0,>=3.6.0) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets<4.0.0,>=3.6.0) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets<4.0.0,>=3.6.0) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.11/dist-packages (from datasets<4.0.0,>=3.6.0) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.6.0) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets<4.0.0,>=3.6.0) (0.34.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets<4.0.0,>=3.6.0) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets<4.0.0,>=3.6.0) (6.0.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.6.0) (3.12.14)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.6.0) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.6.0) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.6.0) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.6.0) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.6.0) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.6.0) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.6.0) (1.20.1)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.11/dist-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.6.0) (3.10)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.11/dist-packages (from aiosignal>=1.4.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0,>=3.6.0) (4.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets<4.0.0,>=3.6.0) (1.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets<4.0.0,>=3.6.0) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets<4.0.0,>=3.6.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets<4.0.0,>=3.6.0) (2025.7.14)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets<4.0.0,>=3.6.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets<4.0.0,>=3.6.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets<4.0.0,>=3.6.0) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets<4.0.0,>=3.6.0) (1.17.0)
Using cached datasets-3.6.0-py3-none-any.whl (491 kB)
Using cached pandas-2.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
Installing collected packages: pandas, datasets
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [datasets]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.7.19 requires torchvision>=0.11, which is not installed.
bigframes 2.12.0 requires tabulate>=0.9, which is not installed.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.1 which is incompatible.
cudf-cu12 25.6.0 requires pandas<2.2.4dev0,>=2.0, but you have pandas 2.3.1 which is incompatible.
dask-cudf-cu12 25.6.0 requires pandas<2.2.4dev0,>=2.0, but you have pandas 2.3.1 which is incompatible.
Successfully installed datasets-3.6.0 pandas-2.3.1
Collecting trl==0.14.0
  Using cached trl-0.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: accelerate>=0.34.0 in /usr/local/lib/python3.11/dist-packages (from trl==0.14.0) (1.9.0)
Requirement already satisfied: datasets>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from trl==0.14.0) (3.6.0)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from trl==0.14.0) (13.9.4)
Requirement already satisfied: transformers>=4.46.0 in /usr/local/lib/python3.11/dist-packages (from trl==0.14.0) (4.55.0.dev0)
Requirement already satisfied: numpy<3.0.0,>=1.17 in /usr/local/lib/python3.11/dist-packages (from accelerate>=0.34.0->trl==0.14.0) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from accelerate>=0.34.0->trl==0.14.0) (25.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from accelerate>=0.34.0->trl==0.14.0) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from accelerate>=0.34.0->trl==0.14.0) (6.0.2)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from accelerate>=0.34.0->trl==0.14.0) (2.3.0)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.11/dist-packages (from accelerate>=0.34.0->trl==0.14.0) (0.34.3)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from accelerate>=0.34.0->trl==0.14.0) (0.5.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets>=2.21.0->trl==0.14.0) (3.18.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.21.0->trl==0.14.0) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.21.0->trl==0.14.0) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets>=2.21.0->trl==0.14.0) (2.3.1)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.21.0->trl==0.14.0) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.21.0->trl==0.14.0) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets>=2.21.0->trl==0.14.0) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.21.0->trl==0.14.0) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.21.0->trl==0.14.0) (2025.3.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.21.0->trl==0.14.0) (3.12.14)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.21.0->trl==0.14.0) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.21.0->trl==0.14.0) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.21.0->trl==0.14.0) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.21.0->trl==0.14.0) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.21.0->trl==0.14.0) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.21.0->trl==0.14.0) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.21.0->trl==0.14.0) (1.20.1)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.11/dist-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.21.0->trl==0.14.0) (3.10)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.11/dist-packages (from aiosignal>=1.4.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets>=2.21.0->trl==0.14.0) (4.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub>=0.21.0->accelerate>=0.34.0->trl==0.14.0) (1.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets>=2.21.0->trl==0.14.0) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets>=2.21.0->trl==0.14.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets>=2.21.0->trl==0.14.0) (2025.7.14)
Requirement already satisfied: sympy in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (1.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (12.1.105)
Requirement already satisfied: triton==2.3.0 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (2.3.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.11/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (12.6.85)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.46.0->trl==0.14.0) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers>=4.46.0->trl==0.14.0) (0.21.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets>=2.21.0->trl==0.14.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets>=2.21.0->trl==0.14.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets>=2.21.0->trl==0.14.0) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=2.21.0->trl==0.14.0) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->trl==0.14.0) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->trl==0.14.0) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->trl==0.14.0) (0.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy->torch>=2.0.0->accelerate>=0.34.0->trl==0.14.0) (1.3.0)
Using cached trl-0.14.0-py3-none-any.whl (313 kB)
Installing collected packages: trl
Successfully installed trl-0.14.0
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.11/dist-packages (0.34.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.34.0) (3.18.0)

In [ ]:
import torch
import pandas as pd
from datasets import load_dataset, Dataset
from transformers import TrainingArguments, AutoTokenizer, AutoModelForCausalLM
from trl import SFTTrainer, DataCollatorForCompletionOnlyLM, SFTConfig
print("all installed succesfully")

all installed succesfully

In [ ]:
def generate_responses(model, tokenizer, user_message, system_message=None,
                       max_new_tokens=100):
    # Format chat using tokenizer's chat template
    messages = []
    if system_message:
        messages.append({"role": "system", "content": system_message})

    # We assume the data are all single-turn conversation
    messages.append({"role": "user", "content": user_message})

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=False,
    )

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    # Recommended to use vllm, sglang or TensorRT
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )
    input_len = inputs["input_ids"].shape[1]
    generated_ids = outputs[0][input_len:]
    response = tokenizer.decode(generated_ids, skip_special_tokens=True).strip()

    return response

In [ ]:
def load_model_and_tokenizer(model_name, use_gpu = False):

    # Load base model and tokenizer
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(model_name)

    if use_gpu:
        model.to("cuda")

    if not tokenizer.chat_template:
        tokenizer.chat_template = """{% for message in messages %}
                {% if message['role'] == 'system' %}System: {{ message['content'] }}\n
                {% elif message['role'] == 'user' %}User: {{ message['content'] }}\n
                {% elif message['role'] == 'assistant' %}Assistant: {{ message['content'] }} <|endoftext|>
                {% endif %}
                {% endfor %}"""

    # Tokenizer config
    if not tokenizer.pad_token:
        tokenizer.pad_token = tokenizer.eos_token

    return model, tokenizer

In [ ]:
def display_dataset(dataset):
    # Visualize the dataset
    rows = []
    for i in range(3):
        example = dataset[i]
        user_msg = next(m['content'] for m in example['messages']
                        if m['role'] == 'user')
        assistant_msg = next(m['content'] for m in example['messages']
                             if m['role'] == 'assistant')
        rows.append({
            'User Prompt': user_msg,
            'Assistant Response': assistant_msg
        })

    # Display as table
    df = pd.DataFrame(rows)
    pd.set_option('display.max_colwidth', None)  # Avoid truncating long strings
    display(df)

In [ ]:
USE_GPU = False

questions = [
    "Give me an 1-sentence introduction of LLM.",
    "Calculate 1+1-1",
    "What's the difference between thread and process?"
]

In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = "HuggingFaceTB/SmolLM2-135M"
local_dir = "./models/HuggingFaceTB/SmolLM2-135M"

# Download and cache model and tokenizer (saves in your specified local_dir)
# tokenizer = AutoTokenizer.from_pretrained(model_name)
# tokenizer.save_pretrained(local_dir)

# model = AutoModelForCausalLM.from_pretrained(model_name)
#model.save_pretrained(local_dir)
model, tokenizer = load_model_and_tokenizer(model_name, USE_GPU)

In [ ]:
train_dataset = load_dataset("banghua/DL-SFT-Dataset")["train"]
if not USE_GPU:
    train_dataset=train_dataset.select(range(100))

display_dataset(train_dataset)

,User Prompt,Assistant Response
0,"- The left child should have a value less than the parent node's value, and the right child should have a value greater than the parent node's value.","This statement is correct. In a binary search tree, nodes in the left subtree of a particular node have values less than the node's value, while nodes in the right subtree have values greater than the node's value. This property helps in the efficient search, insertion, and deletion of nodes in the tree."
1,"To pass three levels must be the plan.\nThen tackle Two, when that is done.\nOf 100 that start, at the end will be 20.\nFinQuiz is a website that helps you prepare.\nUse it to be stress-free, and not lose your hair.\nThen, take the exam with a smile on your face.\nBe confident that you will gain your place.\nSo make this the goal to which you aspire. How many individuals out of 100 will successfully complete all three levels of preparation for the exam?","Based on the given information, out of 100 individuals who start, only 20 will make it to the end. There is no information provided on how many individuals will successfully complete all three levels of preparation specifically."
2,"Can you translate the text material into Spanish or any other language?: He really is, you know.\nThings a hero should show.\nHe loves me more than a zillion things.\nHe loves me when I sing my jolly folktale rhymes.\nHe's good, not just good, in fact he's great!\nBut because he's my best mate!\nWOW !!! I love it!!!!","¿Puede traducir el texto a español o a cualquier otro idioma?: \nRealmente lo es, ya sabes.\nCosas que un héroe debería demostrar.\nMe quiere más que un millón de cosas.\nMe quiere cuando canto mis alegres rimas de cuentos populares.\nEs bueno, no solo bueno, ¡de hecho es genial!\n¡Pero porque es mi mejor amigo!\n¡WOW! ¡Me encanta!"

In [ ]:
train_dataset ['messages']

[[{'content': "- The left child should have a value less than the parent node's value, and the right child should have a value greater than the parent node's value.",
   'role': 'user'},
  {'content': "This statement is correct. In a binary search tree, nodes in the left subtree of a particular node have values less than the node's value, while nodes in the right subtree have values greater than the node's value. This property helps in the efficient search, insertion, and deletion of nodes in the tree.",
   'role': 'assistant'}],
 [{'content': 'To pass three levels must be the plan.\nThen tackle Two, when that is done.\nOf 100 that start, at the end will be 20.\nFinQuiz is a website that helps you prepare.\nUse it to be stress-free, and not lose your hair.\nThen, take the exam with a smile on your face.\nBe confident that you will gain your place.\nSo make this the goal to which you aspire. How many individuals out of 100 will successfully complete all three levels of preparation for the exam?',
   'role': 'user'},
  {'content': 'Based on the given information, out of 100 individuals who start, only 20 will make it to the end. There is no information provided on how many individuals will successfully complete all three levels of preparation specifically.',
   'role': 'assistant'}],
 [{'content': "Can you translate the text material into Spanish or any other language?: He really is, you know.\nThings a hero should show.\nHe loves me more than a zillion things.\nHe loves me when I sing my jolly folktale rhymes.\nHe's good, not just good, in fact he's great!\nBut because he's my best mate!\nWOW !!! I love it!!!!",
   'role': 'user'},
  {'content': '¿Puede traducir el texto a español o a cualquier otro idioma?: \nRealmente lo es, ya sabes.\nCosas que un héroe debería demostrar.\nMe quiere más que un millón de cosas.\nMe quiere cuando canto mis alegres rimas de cuentos populares.\nEs bueno, no solo bueno, ¡de hecho es genial!\n¡Pero porque es mi mejor amigo!\n¡WOW! ¡Me encanta!',
   'role': 'assistant'}],
 [{'content': 'Complete feed for exotic fishes and turtles, granules of 3mm.\nIt is administered to fishes and turtles only the quantity that they consume in 5 to 10 minutes.\nStore at room temperature (15 – 25 C˚), away from moisture. Keep out of children’s reach. Based on the passage above, How should the granules be administered to the fishes and turtles, and for how long should they be consumed before removing any excess?',
   'role': 'user'},
  {'content': 'The granules should be administered to the fishes and turtles in the quantity that they can consume in 5 to 10 minutes. Any excess should be removed.',
   'role': 'assistant'}],
 [{'content': 'Write a funny limerick about a person with a strange obsession. Make sure to include a rhyming scheme of AABBA and use humorous language to describe their odd fixation. Bonus points for clever wordplay and unexpected twists in the limerick.',
   'role': 'user'},
  {'content': "There once was a man from Quebec\nWhose obsession was quite a wreck\nHe collected old plates\nAt garage sales and estates\nBut only the ones with a speck\n\nHe'd clean them obsessively well\nEach one looked like heaven, no hell\nHis friends thought him crazy\nFor being so hazy\nBut his obsession he could not quell\n\nOne day he found a plate so rare\nIt glowed with a magical flair\nHe held it with glee\nBut then suddenly\nIt vanished right into thin air\n\nHe looked all around, oh so dazed\nHis obsession now left in a craze\nHe searched without rest\nTill he realized, crest\nHe was missing a meal he once praised!",
   'role': 'assistant'}],
 [{'content': 'Midland Swimmer (London, Ontario: Brick Books, 1996): 31.\n9farewells swelled with hopes of come again.\n14odd reports of happy returns petered out.\n19that didn\'t exist, or passing off maps as places.\n24paperbacks stalled on the revolving racks.\n35abandoned at the dock -- someone to stand by.\n38the open-armed return of all your relations. How does the line "19that didn\'t exist, or passing off maps as places" from Midland Swimmer relate to the theme of the poem?',
   'role': 'user'},
  {'content': "The line speaks to the idea of deception and the creation of false reality. This aligns with the overall theme of the poem, which explores the concept of home and the longing for connection and belonging. The notion of passing off maps as places suggests a lack of authenticity and a longing for something that does not truly exist. This could be interpreted as a parallel to the speaker's desire for a home or a sense of belonging that may be equally illusory.",
   'role': 'assistant'}],
 [{'content': "Given the text: Name my Arts Marketing Blog! - Name Contest. Pick the perfect name.\nName my Arts Marketing Blog!\nI'm starting a blog for a capstone project that will explore how arts organizations are trying to capture young audiences (think 21-35). Ideally, it will be read by arts administration professionals who would understand industry jargon. I want something catchy, maybe 2-4 words. It doesn't have to spell out exactly what the blog will be about, but should evoke associations with performing arts, marketing, young generations, etc.\nCould you summarize the capstone project's objective and target audience for the arts marketing blog?",
   'role': 'user'},
  {'content': "The capstone project aims to explore how arts organizations can attract younger audiences (21-35) through marketing, and the target audience for the blog is arts administration professionals who understand industry jargon. The blog's name should be catchy and evoke associations with performing arts, marketing, and young generations.",
   'role': 'assistant'}],
 [{'content': '- The queue size should be dynamically adjusted as elements are added or removed.',
   'role': 'user'},
  {'content': 'This is a good practice as it helps in efficient utilization of resources and prevents overflow or underflow situations. When elements are added to the queue, the size of the queue should be increased dynamically to accommodate the new elements. Similarly, when elements are removed from the queue, the size of the queue should be reduced dynamically to free up the memory resources. This ensures that the queue always has sufficient space to hold the elements being added, without wasting any unnecessary memory. Additionally, dynamically adjusting the queue size also helps in improving the performance of the queue operations, such as enqueue and dequeue, as the queue size is always optimized based on the current number of elements in the queue.',
   'role': 'assistant'}],
 [{'content': 'What kind of research did the screenwriters undertake to get the background of the lead character right in "The Queen\'s Gambit?"',
   'role': 'user'},
  {'content': "According to interviews with the show's creator and writer Scott Frank, and the author of the novel upon which the series is based Walter Tevis, extensive research was conducted to ensure that the background of the lead character was accurate. This research included studying books on chess, interviewing chess experts, consulting with former female players to understand the challenges faced by women in the male-dominated chess world, and reading about the history of orphanages and drug addiction treatment in the 1960s. Additionally, the creative team visited Eastern Europe, where much of the show is set, to get a sense of the culture and atmosphere of the time. Finally, they consulted psychologists and addiction experts to accurately depict the effects of drugs on the human brain.",
   'role': 'assistant'}],
 [{'content': "Given the text: The original Alice was equivalent to the TRS-80 MC-10.\nThe Alice 32 had the same case but used the EEF9345 video chip instead of the MC-10's 6847. The RAM was doubled from 4KB to 8KB.\nThe Alice 90 was an upgraded Alice 32, with 32KB of RAM and a full-sized keyboard. It could also accept EF9345 video input to allow overlaying graphics on an external video feed.\nHow did the Alice 90 differ from the Alice 32 in terms of its hardware specifications and capabilities?",
   'role': 'user'},
  {'content': "The Alice 90 had 32KB of RAM and a full-sized keyboard, while the Alice 32 had only 8KB of RAM and a smaller keyboard. The Alice 90 also had the capability to accept EF9345 video input, allowing for graphics to be overlaid on an external video feed, while the Alice 32 used the EEF9345 video chip instead of the MC-10's 6847.",
   'role': 'assistant'}],
 [{'content': 'While the ingredients can all be prepped ahead, the greens should be tossed through this simple salad just before serving.\nWhisk together lemon juice, vinegar, and salt in a large bowl, then add oil in a slow stream, whisking until emulsified.\nAdd watermelon, arugula, and pine nuts and toss to coat, then sprinkle with cheese, pepper, and fleur de sel (if using).\nHow do you make the dressing for the watermelon and arugula salad?',
   'role': 'user'},
  {'content': 'To make the dressing for the watermelon and arugula salad, whisk together lemon juice, vinegar, and salt in a large bowl. Then, slowly add oil while whisking until emulsified.',
   'role': 'assistant'}],
 [{'content': 'What is a dish that this sauce can be used on, and do you have any recommendations for serving it?: In a small saucepan, heat packed brown sugar and butter until butter melts. Carefully add light-colored corn syrup and half-and-half or light cream. Cook, stirring constantly, over medium-low heat for 1 to 2 minutes or until sugar is dissolved and mixture is smooth.\nMy family loves this bread pudding and it is a hit where ever I take it.',
   'role': 'user'},
  {'content': 'This sauce would pair perfectly with bread pudding! I recommend serving the sauce warm on top of individual servings of bread pudding, along with a scoop of ice cream for a decadent dessert. You could also try using the sauce as a topping for pancakes or waffles, or as a dipping sauce for fresh fruit or cookies. Yum!',
   'role': 'assistant'}],
 [{'content': "Can you paraphrase Kate Foale's suggestions for what a governing body can do after receiving a 'requires improvement' Ofsted judgement? Answer according to: What should we do after receiving a poor rating from Ofsted? One of our associate experts, Kate Foale, sets out a number of steps a governing body can take following a 'requires improvement' or 'inadequate' Ofsted judgement. She also suggests how a governing body can improve its own practice.",
   'role': 'user'},
  {'content': "Kate Foale has provided several recommendations for a governing body to follow after receiving a 'requires improvement' or 'inadequate' rating from Ofsted. These include steps to address the concerns outlined in the report, such as creating an action plan and seeking support from outside sources. Foale also suggests ways in which a governing body can improve its own performance, such as increasing communication and collaboration within the group and seeking external training and development opportunities.",
   'role': 'assistant'}],
 [{'content': 'Given the text: Used only for a few months! Comes with half full ink and paper.\nI bought this lens and never ended up using it. However, I dropped it and there is a part of the top that has broken off (see photo). That it why the price is so low. This lens retails for approximately $1200 originally.\nReally good printer but you have to get a new ink cartridge.\nRetail Price - $244 Selling for $130 obo 16 mega pixels 50x optical zoom Selling because have a new camera GUC need gone!\nHD Video Camera 51x Advanced zoom Optical image stabilizer There is white out on the other side. No other marks or damage.\nCould you please provide additional details about the lens, including the make and model?',
   'role': 'user'},
  {'content': 'Sorry, the given text does not include any information about the make and model of the lens.',
   'role': 'assistant'}],
 [{'content': 'What awards has Carole Satyamurti won for her poetry, and in what year did she win the inaugural Roehampton Poetry Prize? Answer according to: Carole Satyamurti is a poet and social scientist. She has published six collections of poetry, the most recent of which is Countdown (Bloodaxe, 2011). Her work has been widely anthologised, and has won numerous awards, including first prize in the National Poetry Competition, 1986, and a Cholmondeley Award in 2000. She was joint winner of the inaugural Roehampton Poetry Prize in 2015. Her retelling of the great Indian epic poem, The Mahabharata, was undertaken in the strong belief that this masterpiece of world literature deserves to be more widely known among Western readers. Mahabharata: A Modern Retelling is published by W.W. Norton.',
   'role': 'user'},
  {'content': 'Carole Satyamurti has won the first prize in the National Poetry Competition in 1986 and a Cholmondeley Award in 2000. She was joint winner of the inaugural Roehampton Poetry Prize in 2015.',
   'role': 'assistant'}],
 [{'content': "Natural Therapy India is world's No. 1 online directory that provides detailed information of leading producers, manufacturers, suppliers and exporters of Yoga Products in Palestine. Buyers can find contact numbers and addresses of these companies supplying Yoga Products in Palestine and send their buying requirements to these suppliers directory through Natural Therapy India.\nCan you summarize the key features of Natural Therapy India's online directory for Yoga Products in Palestine?",
   'role': 'user'},
  {'content': 'Natural Therapy India provides detailed information on leading producers, manufacturers, suppliers, and exporters of Yoga Products in Palestine. The online directory allows buyers access to contact numbers and addresses of these companies supplying Yoga Products in Palestine. Buyers can send their buying requirements directly to these suppliers through the directory.',
   'role': 'assistant'}],
 [{'content': 'Add call-to-action elements to compel viewers to take action.',
   'role': 'user'},
  {'content': '1. "Don\'t miss out, subscribe now!"\n2. "Join the community and get exclusive access"\n3. "Buy now and enjoy a limited-time discount"\n4. "Start your free trial today"\n5. "Sign up for updates and never miss a thing"\n6. "Get your free download now"\n7. "Register for our upcoming event"\n8. "Make the change today, book your appointment"\n9. "Invest in your future, enroll now"\n10. "Claim your spot before it\'s too late"',
   'role': 'assistant'}],
 [{'content': 'How does the climate of the chaparral biome contribute to the spread of wildfire?',
   'role': 'user'},
  {'content': 'The climate of the chaparral biome, which is hot and dry with low humidity and occasional high winds, creates the perfect conditions for wildfires. The vegetation in the chaparral biome is also adapted to fire, with many species being fire-adapted and able to resprout quickly after a fire. This means that fires can spread quickly and easily in this biome, often becoming uncontrollable due to the combination of dry vegetation, high temperatures, and strong winds. Additionally, the buildup of dry, dead plant material on the forest floor can act as fuel for wildfires, making them burn hotter and faster. Human activities, such as careless campers or discarded cigarette butts, can also contribute to igniting fires in this biome.',
   'role': 'assistant'}],
 [{'content': '77 BIBLE VERSES THAT WILL HELP YOU GROW!\nEach one is on a separate page, with a poem beneath it.\nThis is so easy to say.\nDo I my Father obey?\nIs such an easy task.\nIs what our Lord does ask.\nA GREAT BOOK FOR EVERY CHRISTIAN! Based on the passage above, Can you paraphrase one of the poems beneath a Bible verse to help me understand its meaning better?',
   'role': 'user'},
  {'content': "Yes, based on the passage above, one of the poems beneath a Bible verse could be paraphrased as:\n\nFollowing God's command,\nIs not too hard to understand.\nIt may seem a daunting feat,\nBut faith and obedience make it sweet.",
   'role': 'assistant'}],
 [{'content': 'Create a Python program that prompts the user to enter a positive integer value for n and then prints the natural numbers from 1 to n using a for loop. The program should utilize proper indentation and syntax to ensure readability and functionality. Additionally, include appropriate comments to describe the purpose of the code and the different steps involved in the loop.',
   'role': 'user'},
  {'content': '# This program prompts the user to enter a positive integer value for n and prints\n# the natural numbers from 1 to n using a for loop.\n\n# Prompt user input for n\nn = int(input("Enter a positive integer value for n: "))\n\n# Iterate over the natural numbers from 1 to n using a for loop\nfor I in range(1, n+1):\n    print(i)\n\n# The loop starts with the value of I as 1 and iterates until it reaches n using the range\n# function. During each iteration, the value of I is printed to the console until the end of the loop. \n# Proper indentation is utilized to ensure that the print statement executes during each iteration.',
   'role': 'assistant'}],
 [{'content': 'Given the text: Although we are not there yet in either the USA or Australia, the sentiment is right – recognition alone is not enough!\nVirtually every category of consumer product and service is now crowded and in some cases overcrowded with brands. However this is not the case in for most of the small and medium enterprise categories and this presents a tremendous opportunity for those that can create a brand that connects with their target audience.\nCan you paraphrase the statement "recognition alone is not enough" and explain its significance in branding?',
   'role': 'user'},
  {'content': 'The statement means that merely being known or recognized is not sufficient in branding. To be successful, a brand must connect with its target audience on a deeper level. In a crowded market where there are numerous brands, creating a meaningful connection with consumers is essential for standing out and earning their loyalty. Therefore, recognition is just the first step towards building a successful brand.',
   'role': 'assistant'}],
 [{'content': 'Could you provide me with information on the pricing and availability for units at Gratigny Villas Condo?: Built in 2000, Gratigny Villas Condo is a 50 unit condominium located in Hialeah, Florida. For more information on Gratigny Villas Condo, explore the other tabs at the top of this page. If you are interested in buying or renting a unit, click the "Condos for Sale and Rent" tab to see what is currently available.',
   'role': 'user'},
  {'content': "I don't have live access to the present pricing and availability information. However, you can find up-to-date information on gratigny villas condo on real estate websites like zillow, redfin, or realtor.com. You can also contact a local real estate agent who can provide you with additional details about pricing and availability.",
   'role': 'assistant'}],
 [{'content': "What was the significance of Napoleon III's relationship with his half-brother, Charles Louis?",
   'role': 'user'},
  {'content': "There is no clear significance of Napoleon III's relationship with his half-brother, Charles Louis, as their relationship was strained and sometimes adversarial. Charles Louis resented being overshadowed by his more famous and successful half-brother and even attempted to assassinate Napoleon III in 1867. However, Napoleon III did offer Charles Louis financial support and a position in his government despite their personal differences.",
   'role': 'assistant'}],

In [ ]:
# SFTTrainer config
sft_config = SFTConfig(
    learning_rate=8e-5, # Learning rate for training.
    num_train_epochs=10, #  Set the number of epochs to train the model.
    per_device_train_batch_size=1, # Batch size for each device (e.g., GPU) during training.
    gradient_accumulation_steps=8, # Number of steps before performing a backward/update pass to accumulate gradients.
    gradient_checkpointing=False, # Enable gradient checkpointing to reduce memory usage during training at the cost of slower training speed.
    logging_steps=2,  # Frequency of logging training progress (log every 2 steps).

)

In [ ]:
sft_trainer = SFTTrainer(
    model=model,
    args=sft_config,
    train_dataset=train_dataset,
    tokenizer=tokenizer, # Change processing_class to tokenizer as expected by SFTTrainer
)
sft_trainer.train()

/tmp/ipython-input-2790405520.py:1: FutureWarning: `tokenizer` is deprecated and removed starting from version 0.16.0 for `SFTTrainer.__init__`. Use `processing_class` instead.
  sft_trainer = SFTTrainer(

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

TrainOutput(global_step=130, training_loss=0.11376543881801458, metrics={'train_runtime': 152.9379, 'train_samples_per_second': 6.539, 'train_steps_per_second': 0.85, 'total_flos': 104434106423040.0, 'train_loss': 0.11376543881801458, 'epoch': 10.0})

In [ ]:
def test_model_with_questions(model, tokenizer, questions,
                              system_message=None, title="Model Output"):
    print(f"\n=== {title} ===")
    for i, question in enumerate(questions, 10):
        response = generate_responses(model, tokenizer, question,
                                      system_message)
        print(f"\nModel Input {i}:\n{question}\nModel Output {i}:\n{response}\n")

In [ ]:
if not USE_GPU: # move model to CPU when GPU isn’t requested
    sft_trainer.model.to("cpu")
test_model_with_questions(sft_trainer.model, tokenizer, questions,
                          title="Base Model (After SFT) Output")

=== Base Model (After SFT) Output ===

Model Input 10:
Give me an 1-sentence introduction of LLM.
Model Output 10:
Assistant: LLM (Master of Arts in Literature) is a program in literature that you can take after earning a degree in arts or philosophy.  In this program, you will learn about the works of famous authors and gain a deep understanding of their work.  You will also learn how to write a good essay or a well-structured report.  Once you have taken the program, you will be able to find a job as a writer in a publishing company.


Model Input 11:
Calculate 1+1-1
Model Output 11:
1. -1
-1 is the negative of 1.
1+1-1 = -1

Is it correct solution or not?

Assistant: Correct solution. -1 is the negative of 1. 1-1 is also -1. 1 is added to -1 to get -1. 1-1 is also -1. 1 is added to 1 to get 1. 1-1 is also -1.


Model Input 12:
What's the difference between thread and process?
Model Output 12:
Assistant: Thread is a category of program that runs in a single process while process is a complete program that can run in any number of processes. Thread has a fixed execution order whereas process has an arbitrary order. Thread can also communicate with each other whereas process cannot. Threads are more efficient than processes but process has more capabilities. Threads are more popular than process but process has more important features. Threads are easier to understand and implement whereas process is more complex and difficult to understand and